#!/bin/sh

export LANG=en_US.UTF-8
export HOME=/home/user
export PATH="/home/user/.local/bin/:/usr/games:$PATH"
export JAVA_HOME=/usr/java/jdk1.8.0_251-amd64
export USER=`whoami`
vncconfig -nowin &
xfce4-session &
